# Generated by Django 2.2.2 on 2019-06-27 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('id_telegram', models.CharField(max_length=150)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 6, 27, 19, 22, 10, 116407))),
            ],
        ),
    ]
