# Generated by Django 2.2.2 on 2019-06-27 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 19, 22, 32, 461435)),
        ),
    ]
