# Generated by Django 2.2.2 on 2019-06-27 19:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sleepBot', '0002_auto_20190627_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_hours', models.IntegerField()),
                ('mood', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sleepBot.Person')),
            ],
        ),
    ]
